// Host tools. The BER tags/bytes come from the bundled load, not result schemas.
export const VotaLoadFormat = (() => {
 const cp=new TextDecoder('windows-1252'), inverse=new Map();
 for(let i=0;i<256;i++)inverse.set(cp.decode(Uint8Array.of(i)),i);
 const hex=b=>Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');
 function unhex(s){if(typeof s!=='string'||!/^(?:[a-f0-9]{2})*$/i.test(s))throw Error('Esperados bytes em hexadecimal (número par de dígitos)');return Uint8Array.from(s.match(/../g)||[],x=>parseInt(x,16));}
 function textBytes(s){return Uint8Array.from(Array.from(s,c=>{if(!inverse.has(c))throw Error(`O caractere ${c} não existe na codificação da urna (Windows-1252)`);return inverse.get(c)}));}
 function join(parts){const out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let at=0;for(const p of parts){out.set(p,at);at+=p.length}return out;}
 function parse(bytes){let at=0,count=0;function node(end,depth=0){if(depth>64||++count>100000)throw Error('Arquivo BER complexo demais');const start=at,tag=bytes[at++];if(tag===undefined||(tag&31)===31)throw Error('Tag BER não suportada');let size=bytes[at++];if(size===undefined)throw Error('Estrutura BER truncada');if(size&128){const n=size&127;if(!n||n>4||at+n>end)throw Error('Comprimento BER não suportado');size=0;for(let i=0;i<n;i++)size=size*256+bytes[at++];}const stop=at+size;if(stop>end)throw Error('Valor BER truncado');let result={tag};if(tag&32){result.children=[];while(at<stop)result.children.push(node(stop,depth+1));}else{const b=bytes.slice(at,stop);at=stop;if([18,19,22,27].includes(tag))result.text=cp.decode(b);else result.hex=hex(b);}Object.defineProperty(result,'original',{value:bytes.slice(start,at)});Object.defineProperty(result,'snapshot',{value:JSON.stringify(result)});return result;}const result=node(bytes.length);if(at!==bytes.length)throw Error('Dados sobrando depois da estrutura BER');return result;}
 function encode(n,depth=0){if(depth>64||!Number.isInteger(n.tag)||n.tag<0||n.tag>255||(n.tag&31)===31)throw Error('Nó BER inválido');if(n.original&&n.snapshot===JSON.stringify(n))return n.original.slice();const b=(n.tag&32)?join(n.children.map(c=>encode(c,depth+1))):n.text!==undefined?textBytes(n.text):unhex(n.hex);let size=b.length,a=[];do{a.unshift(size&255);size=Math.floor(size/256)}while(size);return join([Uint8Array.of(n.tag,...(b.length<128?[b.length]:[128|a.length,...a])),b]);}
 const base64=b=>{let s='';for(let i=0;i<b.length;i+=8192)s+=String.fromCharCode(...b.subarray(i,i+8192));return btoa(s)};
 const unbase64=s=>{if(typeof s!=='string'||s.length>32*1024*1024)throw Error('Conteúdo em base64 inválido ou grande demais');return Uint8Array.from(atob(s),x=>x.charCodeAt(0))};
 const digest=async b=>hex(new Uint8Array(await crypto.subtle.digest('SHA-256',b)));
 const path=p=>typeof p==='string'&&/^\/dsk\/fi\/(?:estatico\/[a-zA-Z0-9_.-]+|serialv\.dat)$/.test(p)&&!p.includes('..');
 function validateConfig(c){if(!c||!['te','of'].includes(c.fase)||!/^[a-z]{2}$/i.test(c.uf))throw Error('Fase ou UF inválida na configuração');for(const key of ['pe','municipio','zona','secao','turno'])if(!Number.isSafeInteger(c[key])||c[key]<1)throw Error('Valor inválido na configuração: '+key);if(c.turno>2)throw Error('O turno precisa ser 1 ou 2');return c;}
 function validatePackage(p){if(p?.format!=='vota-emulator-load/1'||!Array.isArray(p.files)||p.files.length>2000||typeof p.scenario!=='string')throw Error('Este arquivo não é uma mídia de carga do UrnaEmu');validateConfig(p.config);const names=new Set();let total=0;for(const f of p.files){if(!path(f.path)||names.has(f.path))throw Error('Caminho de arquivo inválido ou repetido na mídia');names.add(f.path);total+=unbase64(f.data).length;if(total>24*1024*1024)throw Error('A mídia passa de 24 MiB');}if(!names.has('/dsk/fi/serialv.dat'))throw Error('Falta o serialv.dat na mídia');return p;}
 const canonical=p=>new TextEncoder().encode(JSON.stringify({format:p.format,scenario:p.scenario,config:p.config,files:p.files.map(f=>({path:f.path,data:f.data})).sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0),...(p.generation?{generation:p.generation}:{}),clock:p.clock||null,inputSignatures:p.inputSignatures||null,identity:p.signature?{algorithm:p.signature.algorithm,spki:p.signature.spki,certificate:p.signature.certificate}:null}));
 async function signPackage(p,provider){validatePackage(p);p.signature={algorithm:provider.algorithm,spki:base64(provider.spki),certificate:base64(provider.certificate)};p.signature.value=base64(await provider.sign(canonical(p)));return p;}
 async function verifyPackage(p,trustedSpki){validatePackage(p);if(!p.signature)return {signed:false,valid:false,trusted:false};const s=p.signature;if(!['P-521','Ed25519'].includes(s.algorithm))throw Error('Algoritmo de assinatura da mídia não suportado');const alg=s.algorithm==='P-521'?{name:'ECDSA',namedCurve:'P-521'}:{name:'Ed25519'};const key=await crypto.subtle.importKey('spki',unbase64(s.spki),alg,false,['verify']);let signature=unbase64(s.value);if(s.algorithm==='P-521'){const tree=parse(signature);if(tree.tag!==48||tree.children?.length!==2)throw Error('Assinatura ECDSA malformada');signature=new Uint8Array(132);tree.children.forEach((n,i)=>{if(n.tag!==2)throw Error('Inteiro malformado na assinatura');let b=unhex(n.hex);if(b[0]===0)b=b.slice(1);if(b.length>66)throw Error('Inteiro grande demais na assinatura');signature.set(b,i*66+66-b.length)});}const valid=await crypto.subtle.verify(s.algorithm==='P-521'?{name:'ECDSA',hash:'SHA-512'}:alg,key,signature,canonical(p));return {signed:true,valid,trusted:valid&&!!trustedSpki&&s.spki===base64(trustedSpki),fingerprint:await digest(unbase64(s.spki))};}
 return {parse,encode,textBytes,hex,unhex,base64,unbase64,digest,validateConfig,validatePackage,canonical,signPackage,verifyPackage};
})();
