// Visible Chrome with a completed native paper capture is required. This UI-only
// regression replays that captured evidence; it does not generate a new ballot.
import{connect,evidencePath}from'../tools/screen-session.mjs';import fs from'node:fs';const b=await connect({evaluationTimeoutMs:180000});try{const result=await b.evaluate(`(async()=>{
 const build=async()=>{if(!urnaEmu.printer.installed)await urnaEmu.printer.install();urnaEmu.printer.replay();};
 await build();const initialPending=urnaEmu.printer.pending;urnaEmu.printer.clear();const clearBacklog=urnaEmu.printer.pending===0&&document.querySelector('[data-testid=printer-paper]').childElementCount===0;
 await build();while(urnaEmu.printer.pending)await new Promise(r=>requestAnimationFrame(r));
 const ops=urnaEmu.paperCapture.state.operations,qr=ops.filter(o=>o.kind==='qr'),canvases=[...document.querySelectorAll('.paper-qr-code')];const pixelExact=qr.length===canvases.length&&qr.every((op,n)=>{const c=canvases[n],d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;return Array.from({length:op.width*op.width},(_,i)=>Boolean(op.bytes[i>>3]&(1<<(i&7)))===(d[i*4]===0)).every(Boolean)});
 const text=ops.filter(o=>o.kind==='text'),spans=[...document.querySelectorAll('.paper-line span')];const alignmentMatches=text.every((op,i)=>spans[i].parentElement.style.textAlign===(op.textAttribute===2?'center':'left'));
 return{operations:ops.length,printedTextBlocks:spans.length,qrBitmaps:qr.length,pixelExact,initialPending,clearBacklog,alignmentMatches,centeredBlocks:text.filter(o=>o.textAttribute===2).length,status:document.querySelector('[data-testid=printer]').dataset.status};
})()`);if(!result.pixelExact||!result.clearBacklog||!result.alignmentMatches||!result.centeredBlocks||result.initialPending!==result.operations)throw Error(JSON.stringify(result));fs.writeFileSync(evidencePath('printer-ui.json'),JSON.stringify({testedAt:new Date().toISOString(),...result},null,2)+'\n');console.log(result);await b.evaluate("document.querySelector('[data-testid=printer]').scrollIntoView({block:'center'});document.querySelector('[data-testid=printer-viewport]').scrollTop=0");await b.delay(500);let shot=await b.call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(evidencePath('printer-desktop.png'),Buffer.from(shot.data,'base64'));await b.call('Emulation.setDeviceMetricsOverride',{width:700,height:1000,deviceScaleFactor:1,mobile:false});await b.evaluate("document.querySelector('[data-testid=printer]').scrollIntoView({block:'center'})");await b.delay(500);shot=await b.call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(evidencePath('printer-narrow.png'),Buffer.from(shot.data,'base64'));await b.call('Emulation.clearDeviceMetricsOverride')}finally{b.close()}
