import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createNativeRuntime} from '#lib/engine/runtime/native-runtime.js';
globalThis.window=globalThis;
globalThis.Module={uenuxDebug:true};
const events=[],logs=[];
globalThis.dispatchEvent=e=>events.push(e);
const buffer=new ArrayBuffer(65536),bytes=new Uint8Array(buffer),view=new DataView(buffer);
const put=(pointer,data)=>{bytes.set(data,pointer);bytes[pointer+data.length]=0;return pointer};
const encode1252=text=>Uint8Array.from([...text].map(c=>c==='“'?0x93:c==='”'?0x94:c.charCodeAt(0)));
// Explicit Windows-1252 dash/quotes distinguish this from ISO-8859-1.
const raw=Uint8Array.from([...encode1252('“Dados dinâmicos não carregados” '),0x97]);
put(4096,raw);view.setUint32(1024,2048,true);view.setUint32(2056,7,true);
const app={exports:{Cb:{buffer},Fb:{get:slot=>{assert.equal(slot,7);return()=>4096}}},tableMetadata:[{slot:7,params:['i32'],result:'i32'}]};
const runtime=createNativeRuntime({app,log:(...args)=>logs.push(args)}),imports={a:{}};
runtime.installImports(imports);
assert.equal(runtime.describeError({excPtr:1024}).message,'“Dados dinâmicos não carregados” —');
imports.a.A(4096);imports.a.Oa(4096);imports.a.J(4096);
assert(logs.every(entry=>entry[1]==='“Dados dinâmicos não carregados” —'));
const reportedError='void comum::CEleitorDetalhe::ConfereDadosDinamicos(const std::string &) const:224:7832 - GetDinamico: Dados dinâmicos não carregados';
put(4096,encode1252(reportedError));
assert.equal(runtime.describeError({excPtr:1024}).message,reportedError);
imports.a.Oa(4096);
assert.deepEqual(logs.at(-1),['error',reportedError]);
put(8192,new TextEncoder().encode('vota:error'));
put(9000,encode1252('{"message":"Dados dinâmicos não carregados"}'));
imports.a.Qa(8192,9000);
assert.equal(events[0].detail.message,'Dados dinâmicos não carregados');
put(9000,new TextEncoder().encode('{"message":"Eleição 🙂"}'));
imports.a.Qa(8192,9000);
assert.equal(events[1].detail.message,'Eleição 🙂');
console.log('PASS: Windows-1252 exceptions/logs/events, smart punctuation, and UTF-8 JSON.');
