import fs from 'node:fs';
import assert from 'node:assert/strict';
import {X509Certificate,verify} from 'node:crypto';
import {createWebCryptoProvider} from '#lib/engine/services/webcrypto-provider.js';
import {VotaPrinterSpool} from '#lib/engine/services/printer-spool.js';
const provider=await createWebCryptoProvider();
const capture=JSON.parse(fs.readFileSync(new URL('../fixtures/printer-operations.json',import.meta.url)));
const ops=capture.operations.filter(o=>['text','newline','cut','qr'].includes(o.kind));
const bytes=VotaPrinterSpool.encode(ops),decoded=VotaPrinterSpool.decode(bytes);
assert.deepEqual(decoded.operations,ops.map(({index,capture,...op})=>op));
const signed=await VotaPrinterSpool.sign(bytes,provider);
assert(await VotaPrinterSpool.verify(bytes,signed,provider));
const envelope=JSON.parse(new TextDecoder().decode(signed).split('\n').slice(1).join('\n'));
assert(verify(null,bytes,new X509Certificate(Buffer.from(envelope.certificate)).publicKey,Buffer.from(envelope.signature)));
const altered=bytes.slice();altered[altered.length-8]^=1;
await assert.rejects(()=>VotaPrinterSpool.verify(altered,signed,provider));
const unrelated=await createWebCryptoProvider();
await assert.rejects(()=>VotaPrinterSpool.verify(bytes,signed,unrelated));
assert.throws(()=>VotaPrinterSpool.decode(new TextEncoder().encode('not a spool')));
assert.throws(()=>VotaPrinterSpool.encode([{kind:'unknown'}]));
console.log('PASS: real captured report round-trip, independent signature verification, tamper and invalid transport rejection.');
